name: blix_signals
version: 0.3.0
author: Nicholas Bilyk <nick@nbilyk.com>
description: Signals are a lightweight, strongly typed observer pattern.
homepage: https://github.com/nbilyk/Signals
environment:
  sdk: '>=0.7.6'
dev_dependencies:
  unittest: any
  benchmark_harness: any
